### ISSUE TITLE
Image Upload fails

### ISSUE THREAD

**Issue by fdaugs** [th-koeln/open-product-evaluation-server#230]
Occasionally the upload of images in the Backend failes with the following server side error and but without any client side error:

`(node:259564) UnhandledPromiseRejectionWarning: Error: Unsupported input boolean
    at Sharp._createInputDescriptor (D:\Daten\FH\ProjektEntwicklung\open-product-evaluation-server\node_modules\sharp\lib\input.js:26:11)
    at new Sharp (D:\Daten\FH\ProjektEntwicklung\open-product-evaluation-server\node_modules\sharp\lib\constructor.js:202:29)
    at Sharp (D:\Daten\FH\ProjektEntwicklung\open-product-evaluation-server\node_modules\sharp\lib\constructor.js:85:12)
    at Promise.all.imageSizes.map (D:\Daten\FH\ProjektEntwicklung\open-product-evaluation-server\src\store\image.store.js:42:24)
    at <anonymous>
(node:259564) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)`

I'm using the current dev Version as of commit 82c770a2e1088cbaf929c1ba905389bda6d48f3e. Like the adjective "occasionally" implies, there are sadly no steps to reproduce.

**Comment by slemke** [comment]
Seems to be fixed in #238. We tried to upload a bunch of files and it didn't throw any errors. If it happens again just reopen this issue.
